fragment PostsParts on Posts {
  __typename
  title
  excerpt
  content
  status
  notify_subscribers
}

fragment ProjectsParts on Projects {
  __typename
  title
  shortTitle
  date
  coverImg
  summary
  industry
  tags
  body
}
