fragment PostsParts on Posts {
  __typename
  slug
  title
  date
  featured
  coverImg
  summary
  category
  tags
  body
}

fragment ProjectsParts on Projects {
  __typename
  title
  shortTitle
  date
  coverImg
  summary
  industry
  tags
  body
}
