version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "monthly"
    versioning-strategy: "lockfile-only"
    open-pull-requests-limit: 3
    groups:
      development:
        patterns:
          - "gulp*"
          - "@11ty*"
          - "browser-sync"
          - "clean-css"
          - "sass"
    ignore:
      - dependency-name: "tinacms"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@11ty/eleventy"
        update-types: ["version-update:semver-major"]
    labels:
      - "dependencies"
      - "dev-only"