 # wrangler.toml
# Cloudflare Pages configuration file

name = "kansei-one"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
destination = "public"

[env.production]
name = "kansei-one-production"

[env.production.vars]
ENVIRONMENT = "production"

# Add your environment variables here (set via Cloudflare dashboard)
# PLUNK_API_KEY = "your-plunk-api-key-here"