name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: write # Changed to write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm install
        npm audit fix || true
        
    - name: Clean Tina cache
      run: |
        rm -rf .tina/cache || true
        rm -rf admin || true
        rm -rf public/admin || true
        
    - name: Initialize Tina
      run: npx tinacms init
      env:
        TINA_CLIENT_ID: ${{ secrets.TINA_CLIENT_ID }}
        TINA_TOKEN: ${{ secrets.TINA_TOKEN }}
        
    - name: Build TinaCMS
      run: |
        mkdir -p admin
        npm run build:tina
      env:
        TINA_CLIENT_ID: ${{ secrets.TINA_CLIENT_ID }}
        TINA_TOKEN: ${{ secrets.TINA_TOKEN }}
        
    - name: Build 11ty
      run: npm run build
      env:
        NODE_ENV: production
        BASE_URL: "/one-kansei"
        
    - name: Copy admin files
      run: |
        mkdir -p public/admin
        cp -r admin/* public/admin/ || true
        
    - name: Create .nojekyll file
      run: |
        touch public/.nojekyll
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './public'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4